// All 98 source cards; see README for source and editorial corrections.
export const sourceUrl =
  "https://quizlet.com/1203332246/spanish-greetings-and-introductions-wes-flash-cards/";
const rows = [
  ["Mucho gusto.", "Pleased/Nice to meet you.", "Greetings", "meet"],
  ["¿Cómo se llama él (ella)?", "What's his (her) name?", "Introductions"],
  ["Adiós.", "Goodbye.", "Greetings"],
  ["Buenas noches.", "Good evening, good night.", "Greetings"],
  ["Buenos días.", "Good morning", "Greetings"],
  ["¡Hola! ¿Cómo estás?", "Hi, how are you? (familiar)", "Greetings"],
  ["Encantado(a).", "Pleased/Nice to meet you.", "Greetings", "meet"],
  ["Igualmente.", "Likewise", "Greetings"],
  ["¿Qué tal?", "What's up?", "Greetings", "whats-up"],
  ["¿Cómo se llama usted?", "What's your name? (formal)", "Introductions"],
  ["¿Cómo te llamas?", "What's your name? (familiar)", "Introductions"],
  ["(Yo) me llamo (name)", "My name is…", "Introductions"],
  ["¿Quién es…?", "Who is…?", "Introductions"],
  ["Yo soy…", "I'm…", "Introductions"],
  ["la chica", "the girl", "Introductions"],
  ["el chico", "the boy", "Introductions"],
  ["mi mejor amigo /a", "my best friend", "Introductions", "best-friend"],
  ["mi mejor amiga", "my best friend (female)", "Introductions", "best-friend"],
  ["el profesor / el maestro", "teacher (male)", "Introductions"],
  ["la compañera de clase", "a (female) classmate", "Introductions"],
  ["el compañero de clase", "a (male) classmate", "Introductions"],
  ["¿De dónde eres?", "Where are you from? (familiar)", "Introductions"],
  ["¿De dónde es usted?", "Where are you from? (formal)", "Introductions"],
  ["Yo soy de…", "I'm from…", "Introductions"],
  ["Hasta pronto.", "See you soon.", "Greetings"],
  ["Más o menos.", "So-so.", "Greetings", "not-well"],
  ["señora (Sra.)", "ma'am, Mrs.", "Introductions"],
  ["Ésta es Rosa / la señora…", "This is Rosa/Mrs.…", "Introductions"],
  ["señorita (Srta.)", "Miss", "Introductions"],
  ["Éste es Juan / el señor…", "This is Juan/Mr.…", "Introductions"],
  ["Tengo que irme.", "I have to go.", "Greetings"],
  ["Estoy bien, gracias.", "I'm fine, thanks.", "Greetings", "well"],
  ["Buenas tardes.", "Good afternoon.", "Greetings"],
  ["Estoy regular/mal.", "I'm all right/not so good.", "Greetings", "not-well"],
  ["Hasta luego.", "See you later.", "Greetings", "see-you"],
  ["Hasta mañana.", "See you tomorrow.", "Greetings", "tomorrow"],
  ["Nos vemos.", "See you.", "Greetings", "see-you"],
  [
    "Mucho gusto en conocerle",
    "Nice to meet you (formal).",
    "Greetings",
    "meet",
  ],
  ["Cuídate.", "Take care.", "Greetings"],
  ["Te presento a…", "Let me introduce you to", "Introductions"],
  ["señor", "sir, Mr.", "Introductions"],
  [
    "Nos vemos mañana / hasta mañana",
    "See you tomorrow",
    "Greetings",
    "tomorrow",
  ],
  ["Perdón / Lo siento", "Excuse me; I'm sorry", "Greetings"],
  ["El gusto es mío", "The pleasure is mine", "Greetings", "pleasure"],
  ["¿Quién eres tú?", "Who are you?", "Introductions"],
  ["¿Dónde vives?", "Where do you live?", "Introductions"],
  ["Yo vivo en…", "I live in…", "Introductions"],
  ["Yo estoy bien, gracias.", "I am well, thank you.", "Greetings", "well"],
  [
    "¿Qué pasa? / ¿Qué tal?",
    "What's up? How's it going?",
    "Greetings",
    "whats-up",
  ],
  ["¿Cuántos años tienes?", "How old are you?", "Introductions"],
  ["¿Cuántos años tiene usted?", "How old are you? (formal)", "Introductions"],
  [
    "¿Cuál es tu color favorito?",
    "What is your favorite color?",
    "Introductions",
  ],
  [
    "¿Cuál es tu número de teléfono?",
    "What is your phone number?",
    "Introductions",
  ],
  [
    "¿Cuál es tu deporte favorito?",
    "What is your favorite sport?",
    "Introductions",
  ],
  ["¿Qué día es hoy?", "What day is today?", "Calendar"],
  ["Hoy es", "Today is…", "Calendar"],
  ["¿Qué fecha es hoy?", "What's today's date?", "Calendar"],
  ["la semana", "week", "Calendar"],
  ["¿Cuándo es tu cumpleaños?", "When is your birthday?", "Calendar"],
  ["Mi cumpleaños es…", "My birthday is…", "Calendar"],
  ["meses del año", "the months of the year", "Calendar"],
  ["enero", "January", "Calendar", null, "months"],
  ["febrero", "February", "Calendar", null, "months"],
  ["marzo", "March", "Calendar", null, "months"],
  ["abril", "April", "Calendar", null, "months"],
  ["mayo", "May", "Calendar", null, "months"],
  ["junio", "June", "Calendar", null, "months"],
  ["julio", "July", "Calendar", null, "months"],
  ["agosto", "August", "Calendar", null, "months"],
  ["septiembre", "September", "Calendar", null, "months"],
  ["octubre", "October", "Calendar", null, "months"],
  ["noviembre", "November", "Calendar", null, "months"],
  ["diciembre", "December", "Calendar", null, "months"],
  ["días de la semana", "the days of the week", "Calendar"],
  ["lunes", "Monday", "Calendar", null, "days"],
  ["martes", "Tuesday", "Calendar", null, "days"],
  ["miércoles", "Wednesday", "Calendar", null, "days"],
  ["jueves", "Thursday", "Calendar", null, "days"],
  ["viernes", "Friday", "Calendar", null, "days"],
  ["sábado", "Saturday", "Calendar", null, "days"],
  ["domingo", "Sunday", "Calendar", null, "days"],
  ["las estaciones", "seasons", "Weather"],
  ["la primavera", "spring", "Weather", null, "seasons"],
  ["el verano", "summer", "Weather", null, "seasons"],
  ["el otoño", "fall", "Weather", null, "seasons"],
  ["el invierno", "winter", "Weather", null, "seasons"],
  ["¿Qué tiempo hace hoy?", "What's the weather like today?", "Weather"],
  ["Hace calor", "It's hot", "Weather"],
  ["Hace frío", "It's cold", "Weather"],
  ["Hace mal tiempo", "It's bad weather", "Weather"],
  ["Hace buen tiempo", "It's good weather", "Weather"],
  ["Hace viento", "It's windy", "Weather"],
  ["Llueve", "It's raining", "Weather"],
  ["Nieva", "It's snowing", "Weather"],
  ["Está nublado", "It's cloudy", "Weather"],
  ["Hay tormentas", "There are storms", "Weather"],
  ["Hay relámpagos", "There's lightning", "Weather"],
  ["Es un placer", "It's a pleasure", "Greetings", "pleasure"],
];
export const cards = rows.map(
  ([es, en, category, equivalent, family], index) => ({
    id: index + 1,
    es,
    en,
    category,
    equivalent: equivalent ?? `card-${index + 1}`,
    family: family ?? category,
  }),
);
